# Generated by Django 3.0.1 on 2022-02-14 00:18

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('clients', '0002_comment'),
    ]

    operations = [
        migrations.CreateModel(
            name='Vehicle',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('make', models.CharField(default=' ', max_length=50)),
                ('model', models.CharField(default=' ', max_length=50)),
                ('VIN_number', models.CharField(default=' ', max_length=50)),
                ('date_of_purchase', models.DateTimeField(null=True)),
                ('date_of_last_service', models.DateTimeField(null=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vehicles', to='clients.Client')),
            ],
        ),
    ]
